name: Security Scanning

on: push

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          target: 'https://georgetroupis.github.io/terminator-state-machine/'
