name: Security Scanning

on: push

jobs:
  steps:
    - name: OWASP ZAP Full Scan
      uses: zaproxy/action-full-scan@v0.4.0
      with:
        target: 'https://georgetroupis.github.io/terminator-state-machine/'
